name: todo_paraguay_sa
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  uno: ^1.0.1+5
  banner_carousel: ^1.2.1
  dartz: ^0.10.1
  flutter_triple: ^1.2.7+4
  flutter_modular: ^5.0.3
  eva_icons_flutter: ^3.1.0
  intl: ^0.17.0
  percent_indicator: ^3.4.0
  timeago: ^3.1.0
  dotted_border: ^2.0.0+1
  mocktail: ^0.3.0

  cambona:
    path: cambona

  common_dependencies:
    path: common_dependencies
    
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartz_test: ^0.1.1

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/todo_paraguay.png
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
